name: CI

on: [pull_request, push]

jobs:
  build-mac:
    env:
      developer-id: ${{ secrets.DEVELOPER_ID }}
    name: Build - macOS
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - run: ./gradlew build updateVersions updateAllDependencies -PbuildServer
        name: Build with Gradle
      
      - run: |
          npm install
          npm run compile
          npm run lint
          npm run packageMac
        name: Build Standalone Utility
        working-directory: wpilib-utility-standalone
            
      - run: tar -pcvzf wpulibutility-mac.tar.gz build/wpilibutility-darwin-x64
        working-directory: wpilib-utility-standalone
        name: Create Archive
      
      - uses: actions/upload-artifact@v2
        with:
          name: wpilibutility-mac
          path: wpilib-utlilty-standalone/wpilibutility-mac.tar.gz
         
