name: CI

on: [pull_request, push]

jobs:
  build-mac:
    name: Build - macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.x'
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build updateVersions updateAllDependencies -PbuildServer
        name: Build with Gradle
      - run: |
          npm install
          npm run compile
          npm run lint
          npm run packageMac
        name: Build Standalone Utility
        working-directory: wpilib-utility-standalone
      - name: Import Developer ID Certificate
        uses: wpilibsuite/import-developer-certificate@v1
        with:
          certificate-data: ${{ secrets.APPLE_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        if: |
          (github.repository_owner == 'wpilibsuite') &&
          (github.refs == 'refs/heads/master' || startsWith(github.refs, 'refs/tags/v'))
      - name: Sign Standalone Utility
        run: npm run signMac
        working-directory: wpilib-utility-standalone
        if: |
          (github.repository_owner == 'wpilibsuite') &&
          (github.refs == 'refs/heads/master' || startsWith(github.refs, 'refs/tags/v'))
      - name: Notarize Standalone Utility
        uses: wpilibsuite/xcode-notarize@v1
        with:
          product-path: "wpilib-utility-standalone/build/wpilibutility-darwin-x64/wpilibutility.app"
          primary-bundle-id: edu.wpi.first.wpilibutility
          appstore-connect-username: ${{ secrets.APPLE_NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.APPLE_NOTARIZATION_PASSWORD }}
        if: |
          (github.repository_owner == 'wpilibsuite') &&
          (github.refs == 'refs/heads/master' || startsWith(github.refs, 'refs/tags/v'))
      - name: Staple Notarization Ticket
        run: xcrun stapler staple -v wpilibutility.app
        working-directory: wpilib-utility-standalone/build/wpilibutility-darwin-x64
        if: |
          (github.repository_owner == 'wpilibsuite') && 
          (github.refs == 'refs/heads/master' || startsWith(github.refs, 'refs/tags/v'))
      - run: tar -C build/wpilibutility-darwin-x64 -pcvzf wpilibutility-mac.tar.gz .
        working-directory: wpilib-utility-standalone
        name: Create Archive
      - uses: actions/upload-artifact@v2
        with:
          name: Mac
          path: ${{ github.workspace }}/wpilib-utility-standalone/wpilibutility-mac.tar.gz

  build-linux:
    name: Build - Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.x'
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build updateVersions updateAllDependencies -PbuildServer
        name: Build with Gradle
      - run: |
          npm install
          npm run compile
          npm run lint
          npm run packageLinux
        name: Build Standalone Utility
        working-directory: wpilib-utility-standalone
      - run: tar -C build/wpilibutility-linux-x64 -pcvzf wpilibutility-linux.tar.gz .
        working-directory: wpilib-utility-standalone
        name: Archive Utility
      - uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: ${{ github.workspace }}/wpilib-utility-standalone/wpilibutility-linux.tar.gz

  build-windows:
    name: Build - Windows Standalone
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.x'
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build updateVersions updateAllDependencies -PbuildServer
        name: Build with Gradle
      - run: |
          npm install
          npm run compile
          npm run lint
          npm run packageWindows
        name: Build Standalone Utility
        working-directory: wpilib-utility-standalone
      - uses: actions/upload-artifact@v2
        with:
          name: WindowsStandalone
          path: wpilib-utility-standalone/build/wpilibutility-win32-ia32

  build-windows-vsix:
    name: Build - Windows VSIX
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.x'
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build updateVersions updateAllDependencies -PbuildServer
        name: Build with Gradle
      - run: |
          npm install
          npm run lint
          npm run unittest
          npm run gulp
          npm run webpack
          npm run vscePackage
        working-directory: vscode-wpilib
        name: Build VSIX
      - uses: actions/upload-artifact@v2
        with:
          name: WindowsVSIX
          path: ${{ github.workspace }}/**/*.vsix
